modules = ["python-3.11", "python3"]

[nix]
channel = "stable-24_05"

[workflows]
runButton = "NotionNLP Example"

[[workflows.workflow]]
name = "NotionNLP Example"
author = "agent"

[workflows.workflow.metadata]
agentRequireRestartOnSave = false

[[workflows.workflow.tasks]]
task = "packager.installForAll"

[[workflows.workflow.tasks]]
task = "shell.exec"
args = "python examples/check_access.py"

[deployment]
run = [
  "sh", 
  "-c", 
  "python -m spacy download en_core_web_sm && python examples/basic_usage.py"
]
