
modules = ["python-3.11", "python3"]

[nix]
channel = "stable-24_05"

[workflows]
runButton = "Streamlit Demo"

[[workflows.workflow]]
name = "Streamlit Demo"
author = "agent"

[workflows.workflow.metadata]
agentRequireRestartOnSave = false

[[workflows.workflow.tasks]]
task = "packager.installForAll"

[[workflows.workflow.tasks]]
task = "shell.exec"
args = "python -m spacy download en_core_web_sm && streamlit run demo/streamlit_app.py --server.port=8501 --server.address=0.0.0.0 --server.enableCORS=false --server.enableXsrfProtection=false --server.baseUrlPath=''"
waitForPort = 8501

[[ports]]
localPort = 8501
externalPort = 3000
